### ISSUE TITLE
Error is thrown if no host group docker_hosts exists

### ISSUE THREAD

**Issue by nilskuhn** [ryandaniels/ansible-role-iptables-docker#3]
I am getting the following error if I try to run the role:
```
fatal: [performance-infrastructure]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'docker_hosts'\n\nThe error appears to be in '<my-roles-path>/roles/ryandaniels.iptables_docker/tasks/main.yml': line 19, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: iptables Docker | Set Docker server IPs for allow list\n  ^ here\n"}
```
I don't have a group `docker_hosts` in my inventory file. Instead, I am setting the following:
```
iptables_docker_server_ip_allow_set:
  - <my-server-ip>
```
Am I doing something wrong? Or do I need to name my servers group `docker_hosts`?

**Comment by ryandaniels** [comment]
Yes, docker_hosts needs to be present in inventory file:
https://github.com/ryandaniels/ansible-role-iptables-docker#example-inventory-file

**Comment by nilskuhn** [comment]
Feels a bit unusual for me to be forced to name a separate host group in inventory for one of the roles I am applying in a playbook. Wouldn't it be possible to just take all hosts targeted by the current play instead (ansible var `ansible_play_hosts_all`)?

**Comment by ryandaniels** [comment]
You could try using the "children" concept. Or feel free to fork & modify the code to your specific needs.
See: https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
